@startuml
title Step 2: Executing the Add Command

participant "AddFlashcardCommand" as AFC
participant "FlashcardList" as FCL
participant "Flashcard" as FC
participant "Storage" as S
participant "Ui" as Ui

AFC -> FC : new Flashcard(question, answer)
AFC -> FCL : addFlashcard(flashcard)
AFC -> S : writeToFile(flashcards)
AFC -> Ui : showFlashcardAdded(flashcard)
@enduml