@startuml
title Delete — Execution

participant "RemoveFlashcardCommand" as RFC
participant "FlashcardList" as FCL
participant "Flashcard" as FC
participant "Storage" as S
participant "Ui" as Ui

RFC -> RFC : parse/validate index
alt index invalid
    RFC -> Ui : invalidIndexRespond()
else index valid
    RFC -> FCL : getFlashcard(zeroIndex)
    RFC -> FCL : removeFlashcard(zeroIndex)
    RFC -> S : writeToFile(flashcards)
    RFC -> Ui : showFlashcardRemoved(deletedFlashcard)
end
@enduml
