@startuml
title Step 2: Executing the Search Command

participant "SearchFlashcardCommand" as SFC
participant "FlashcardList" as FCL
participant "Flashcard" as FC
participant "Ui" as Ui

SFC -> FCL : getAll()
loop for each flashcard
    SFC -> FC : getQuestion(), getAnswer()
    alt matches key phrase
        SFC -> FCL : addFlashcard(flashcard)
    end
end
alt no matches
    SFC -> Ui : noMatchesRespond()
else
    SFC -> FCL : showList()
end
@enduml